Fix paths on windows
ryukzak/nitta pull request #229
Opened 2022-10-19 18:45 UTC by daniilprohorov

2022-11-25 01:43 UTC, ryukzak commented
Hi, sorry for the long review!

In `NITTA.Utils` you can find: `toModuleName`. This function should transform the text to the correct module name. Can you improve this function and add it to the code where needed?

Also, can you revoke the `testcaseM` function, because I see no reason why we shouldn't use `toModuleName` everywhere?

2023-02-06 01:38 UTC, ryukzak requested changes
- Please, fix code style.
- I don't think that we need to have `testCaseM` function. It should be a part of base `testCase`. Also, looks like you can reduce amount of usage "fix funciton" in the code.

2023-02-06 01:38 UTC, ryukzak commented on test/NITTA/Utils/Tests.hs
> +modifyTestName name = replace " " "_" $ replace ":" "_" name
Rename `modifyTestName` to `fixModuleName`

2023-02-12 16:15 UTC, daniilprohorov commented
![image](https://user-images.githubusercontent.com/22121879/218322776-3f56fc82-a554-47f2-a559-1965d891a334.png)
Are you sure, that we have to use toModuleName everywhere?

2023-02-13 14:10 UTC, ryukzak requested changes

2023-02-13 14:10 UTC, ryukzak commented on src/NITTA/Project.hs
> +            directory <- makeAbsolute $ normalise $ joinPath [fullNittaPath, "lib", takeDirectory file]
Also, can you import `normalise` explicitly or with qualified name?

Please, add small issue to grep our project and find other places when it is reasonable to `normalise` paths for new project members.

2023-02-13 14:10 UTC, ryukzak commented on test/NITTA/Frontends/Lua/Tests.hs
> +      -- , testCaseM "examples/fibonacci.lua drop" $ either assertFailure return
You miss this in the comment:

> I don't think that we need to have testCaseM function. It should be a part of base testCase. Also, looks like you can reduce amount of usage "fix funciton" in the code.

2023-02-13 16:18 UTC, ryukzak commented on test/NITTA/Model/ProcessorUnits/Tests/DSL.hs
> +unitTestCase name pu alg = testCase (toModuleName name) $ do
We don't need it here.

2023-03-03 09:42 UTC, ryukzak approved these changes

2023-03-03 09:42 UTC, merged